export const texts = {
    settings: 'settings',
    eMail:"email",
    password:"password",
    colorTheme:"colorTheme",
    dark:"dark",
    light:"light",
    language:"language",
    english:"english",
    turkish:"turkish",
    signOut:"signOut",
    toDoList:"toDoList",
    login:"login",
    username:"username",
    signUp:"signUp",
    taskname:"taskname",
    endDate:"endDate",
    time:"time",
    today:"today",
    noteDetails:"explanation",
    add:"add",
    addNewNote:"addNewNote",
    completed:"completed",
    edit:"edit",
    categories: "categories",
    home: "home",
    work: "work",
    other: "other"
};

export const english={
    [texts.settings]:"Settings",
    [texts.eMail]:"E-Mail",
    [texts.password]:"Password",
    [texts.colorTheme]:"Color Theme",
    [texts.language]:"Language",
    [texts.english]:"English",
    [texts.turkish]:"Türkçe",
    [texts.toDoList]:"ToDo List",
    [texts.login]:"Login",
    [texts.dark]:"Dark Mode",
    [texts.light]:"Light Mode",
    [texts.signOut]:"Sign Out",
    [texts.username]:"Username",
    [texts.signUp]:"Sign Up",
    [texts.taskname]:"Task Name",
    [texts.endDate]:"End Date",
    [texts.time]:"Time",
    [texts.today]:"Today",
    [texts.noteDetails]:"Note Details...",
    [texts.add]:"Add a New Note",
    [texts.addNewNote]:"Add New Note",
    [texts.completed]:"Completed",
    [texts.edit]:"EDIT",
    [texts.categories]: "Categories",
    [texts.home]: "Home",
    [texts.work]: "Work",
    [texts.other]: "Other"
};

export const turkish ={
    [texts.settings]:"Ayarlar",
    [texts.eMail]:"E-Mail",
    [texts.password]:"Şifre",
    [texts.colorTheme]:"Renk Teması",
    [texts.language]:"Diller",
    [texts.english]:"English",
    [texts.turkish]:"Türkçe",
    [texts.toDoList]:"Yapılacaklar Listesi",
    [texts.login]:"Giriş Yap",
    [texts.dark]:"Siyah Tema",
    [texts.light]:"Beyaz Tema",
    [texts.signOut]:"Çıkış Yap",
    [texts.username]:"Kullanıcı Adı",
    [texts.signUp]:"Kayıt Ol",
    [texts.taskname]:"Görev Adı",
    [texts.endDate]:"Bitiş Tarihi",
    [texts.time]:"Saat",
    [texts.today]:"Bugün",
    [texts.noteDetails]:"Açıklama...",
    [texts.add]:"Yeni Bir Not Ekle",
    [texts.addNewNote]:"Yeni Not Ekle",
    [texts.completed]:"Tamamlananlar",
    [texts.edit]:"DÜZENLE",
    [texts.categories]: "Kategoriler",
    [texts.home]: "Ev",
    [texts.work]: "İş",
    [texts.other]: "Diğer"
};